### ISSUE TITLE
gulp.watch doesn't catch new files

### ISSUE THREAD

**Issue by k-funk** [VARIANTE/generator-vars-jekyll#14]
Seems like using `gulp-watch` is currently the way to go, in order to have new files get noticed/reloaded. http://stackoverflow.com/questions/22391527/gulps-gulp-watch-not-triggered-for-new-or-deleted-files

To see what I'm referring to, start your server, add an image to your images directory, and see that the server was oblivious to the change in that directory.

**Comment by andrewscwei** [comment]
The problem is that currently both `gulp.watch()`and `gulp-watch` are only able to pick up new files if the provided path is relative (see this [issue](https://github.com/floatdrop/gulp-watch/issues/104)). The easiest way to make this work with this generator is to go to `.taskconfig`, edit the `watch` options and change all `sourceDir` (absolute path) to `'app'` (relative path).
