### ISSUE TITLE
Front-End Dependency Management

### ISSUE THREAD

**Issue by k-funk** [VARIANTE/generator-vars-jekyll#5]
First off, thank you for writing this generator. It's probably the most thorough boilerplate for these tasks that I've come across. But anyways...

What was your vision for front-end dependencies (jquery, moment, bootstrap, etc.)? I loathe including them in my repo, and want to take away the Bower crutch. That said, npm is the only avenue I've considered.

I see [here](https://github.com/andrewscwei/generator-vars-jekyll/blob/b8b9620c722d5b5e030c70d455e5a9a56dd575b6/app/templates/.taskconfig#L55) that there's an `.../_assets/vendor` directory. Is that meant for dependencies that just happen to not be in npm?

Would you recommend including dependencies in `.../_assets/javascripts/main.js` with `require('<path_to_bootstrap.js'); var $ = require('jquery');`, and let webpack handle it?

**Comment by andrewscwei** [comment]
Hello, glad to hear you find this generator helpful. To answer your question, this generator was created with the aim to only rely on NPM to manage dependencies—JavaScript or CSS. Like you, I wanted to drop Bower because I didn't want to have two package managers coexist in the same project, namely NPM and Bower. So yes, I strongly recommend just importing/requiring your dependencies managed by NPM In `main.js`.

The `vendor` directory is there to support dependencies that are either not managed by NPM or not written to comply with the CommonJS protocol. Modernizr is a good example, same with other legacy libraries. The Gulp pipeline that comes with this generator will automatically concat all JS files inside the `vendor` directory, ordered by filename, into `vendor.js`, which automatically gets included inside `<head>` of every template. Though if you can, I recommend avoiding the usage of the `vendor` directory and solely rely on NPM instead.

The generator aims to provide a basic boilerplate for a Gulp-pipelined Jekyll project. Most features can be customized. Webpack config, for example, can be tweaked in `.taskconfig`, along with options associated with other Gulp tasks.

Cheers!

**Comment by k-funk** [comment]
Awesome. Thanks for the clarification. Might be worth documenting this in the readme with a couple links to articles [[1]](https://gofore.com/stop-using-bower/) [[2]](http://wesbos.com/javascript-modules/) [[3]](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) about why to follow this pattern. There's plenty of ignorant people (like me) that could benefit from guidance on actually implementing the ideas that these articles suggest.

**Comment by k-funk** [comment]
One more question on this regarding loading fonts/images that are in npm installed packages.

For Example:
`npm install bootstrap-sass`
How do I include the glyphicons font? Setting `$icon-font-path: "bootstrap-sass/assets/fonts/bootstrap/"; @import 'bootstrap-sass/assets/stylesheets/bootstrap';` in `main.scss` isn't good enough since the browser needs access to them. Is there any solution that doesn't require me copying files out of `node_modules` and putting them in my repo? I think webpack has a solution for the fonts, using `file-loader`, but right now webpack is only being used for js assets.

```
{
  test: /\.woff2?$|\.ttf$|\.eot$|\.svg$/,
  loader: 'file',
  query: { name: './fonts/[hash].[name].[ext]'}
},
```

**Comment by andrewscwei** [comment]
You should be able to tweak the `.taskconfig` file to do what you need. I can think of 2 ways:
1. Integrate `file-loader` like you suggested. All Webpack config options are in `.taskconfig`, under `scripts`.
2. Add the path to Bootstrap fonts to `.taskconfig` under `fonts.entry` so it gets copied over by Gulp, like this:
   
   ```
   ...
   fonts: {
       entry: [ // Change this to an array
         path.join(sourceDir, '_assets', 'fonts', '**', '*.{eot,svg,ttf,woff,woff2}'),
         path.join(modulesDir, {PATH_TO_BOOTSTRAP_FONTS}) // Add your path
       ],
       output: path.join(buildDir, 'assets', 'fonts')
     },
   ...
   ```

**Comment by k-funk** [comment]
Since webpack is only handling scripts right now, I think that option 2 is probably best. Thanks for the code sample.
